// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRRLaVpbe0RzKxqCgY94ufX3DQesbwzw0',
    appId: '1:829560051923:web:68cc985f285f69a07adc26',
    messagingSenderId: '829560051923',
    projectId: 'mironline-flutter-project',
    authDomain: 'mironline-flutter-project.firebaseapp.com',
    storageBucket: 'mironline-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABkorIRVvEfCr-i_X7czN-NcMscGak4KY',
    appId: '1:829560051923:android:4ca0bed0db54321f7adc26',
    messagingSenderId: '829560051923',
    projectId: 'mironline-flutter-project',
    storageBucket: 'mironline-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRC60C1pbDYrSKA5bIukTvDGu22RtJugM',
    appId: '1:829560051923:ios:970f6adb262cf1457adc26',
    messagingSenderId: '829560051923',
    projectId: 'mironline-flutter-project',
    storageBucket: 'mironline-flutter-project.appspot.com',
    iosBundleId: 'com.mironline.mironline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRC60C1pbDYrSKA5bIukTvDGu22RtJugM',
    appId: '1:829560051923:ios:126df9c3be3910a57adc26',
    messagingSenderId: '829560051923',
    projectId: 'mironline-flutter-project',
    storageBucket: 'mironline-flutter-project.appspot.com',
    iosBundleId: 'com.mironline.mironline.RunnerTests',
  );
}
